kind: Service
apiVersion: v1
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: adminer
        image: aminer:4.7
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: odoodb-service       
        ports:
        - containerPort: 8080
